apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
  labels:
    app: nodejs
spec:
  containers:
  - name: nodejs
    image: node:18
    command: ["node", "/usr/src/app/server.js"]
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: app-code
      mountPath: /usr/src/app
  volumes:
  - name: app-code
    configMap:
      name: nodejs-app-config
